### ISSUE TITLE
yaml error : did not find url escaped octet

### ISSUE THREAD

**Issue by Bart0101010101** [cloudfoundry/diego-windows-release#10]
The manifest returned from my bosh-lite install when running generate.exe on a Windows VM fails to parse the response from the /deployments/{name} call - it complains about line 1711 of the manifest at generate.go:113

I replicated this running from the generate.go src 

applying the change in:

https://github.com/go-yaml/yaml/issues/75

to gopkg.in\yaml.v2\scannerc.go

Sorted the issue for me and generate.go was able to run without error

I encountered this with: 
cf v226
diego v0.1442.0
bashlite stem v2776
garden-linux v0.328.0
etcd v18
DiegoWindows v237

**Comment by Bart0101010101** [comment]
I can confirm that the generate.exe from v281 also fails in the same way

**Comment by mhoran** [comment]
Hey @Bart0101010101. Thanks for opening this issue! Would you be able to provide a failing deployment manifest so that we can reproduce this locally?

**Comment by Bart0101010101** [comment]
One or or the other or both of these failed, but it was definitely one of these two :-)
http://pastebin.com/cNVQACh1
http://pastebin.com/iJUfCiij
 

    On Tuesday, 19 January 2016, 16:42, Matthew Horan <notifications@github.com> wrote:
 

 Hey @Bart0101010101. Thanks for opening this issue! Would you be able to provide a failing deployment manifest so that we can reproduce this locally?—

**Comment by mhoran** [comment]
Thanks for getting us that, was pretty easy to reproduce. We ended up switching to https://github.com/cloudfoundry-incubator/candiedyaml as it's the preferred Golang YAML parser here.
