### ISSUE TITLE
Need ability to overcommit rep

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/diego-windows-release#16]
On the Linux cells we can set disk and memory overcommit values as such:

https://github.com/cloudfoundry-incubator/diego-release/blob/develop/jobs/rep/templates/rep_ctl.erb#L120-L121

Right now the Windows service has these values hard-coded to "auto":

https://github.com/cloudfoundry/diego-windows-release/blob/master/DiegoWindowsRelease/RepService/RepService.cs#L101-L102

We need to be able to specify overcommit values to get better use of our resources when developers routinely over specify their memory and disk usage.  Please allow configuring new parameters in the MSI setup to allow specifying these values.

**Comment by sbenario** [comment]
@amhuber Thanks for the feedback! I morphed the pivotal tracker story into a feature, which is now being tracked in the backlog.

Cheers

**Comment by mavenraven** [comment]
@amhuber We'll revisit this in a post BOSH Windows world, which I expect will solve your problem. Thanks for your issue!
