### ISSUE TITLE
Generate.exe fails 

### ISSUE THREAD

**Issue by aemruli** [cloudfoundry/diego-windows-release#17]
When installing my Windows cell, executing generate.exe leads to an error. Executing generate.exe -boshUrl=https://director:verySecret@192.168.5.2:25555 -outputDir=C:/diego leads to the exception 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4022f3]

goroutine 1 [running]:
main.fillSharedSecret(0xc082147ed8, 0xc0820f1c00, 0x25, 0x2a, 0x0)
        C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:151 +0x93
main.main()
        C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:124 +0xbfa

goroutine 8 [runnable]:
net/http.(*persistConn).readLoop(0xc08200e160)
        c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc08200e160)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc08200e790)
        c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc08200e790)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3
```

Accessing the bosh director url with the browser shows me all the deployments.

**Comment by sbenario** [comment]
Does the generate.exe version match the right cf version? 
Each release is tested against a specific version of garden and Diego, as listed in the release. 





On Tue, May 24, 2016 at 8:18 AM -0700, "Agim Emruli" <notifications@github.com> wrote:












When installing my Windows cell, executing generate.exe leads to an error. Executing generate.exe -boshUrl=https://director:verySecret@192.168.5.2:25555 -outputDir=C:/diego leads to the exception 

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4022f3]

goroutine 1 [running]:
main.fillSharedSecret(0xc082147ed8, 0xc0820f1c00, 0x25, 0x2a, 0x0)
        C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:151 +0x93
main.main()
        C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:124 +0xbfa

goroutine 8 [runnable]:
net/http.(*persistConn).readLoop(0xc08200e160)
        c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc08200e160)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc08200e790)
        c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:660 +0xca6

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc08200e790)
        c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:661 +0xcc3




Accessing the bosh director url with the browser shows me all the deployments.

**Comment by aemruli** [comment]
@sbenario thanks for the hint. Unfortunately I took a newer version of generate.exe. Closing the ticket.

**Comment by vijaay** [comment]
how to check whether version matches or not
