### ISSUE TITLE
Call of non existing install.bat

### ISSUE THREAD

**Issue by prysmakou** [cloudfoundry/diego-windows-release#2]
After small modification of the template (I just specified my CF/Diego's subnet) debug-stderr contains:
```
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
main.main()
	C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:138 +0x1f5e

goroutine 8 [runnable]:
net/http.(*persistConn).readLoop(0xc08208c0b0)
	c:/go/src/net/http/transport.go:928 +0x9d5
created by net/http.(*Transport).dialConn
	c:/go/src/net/http/transport.go:660 +0xca6

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc08208c0b0)
	c:/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
	c:/go/src/net/http/transport.go:661 +0xcc3
'C:\tmp\dwminst\install.bat' is not recognized as an internal or external command,
operable program or batch file.
```
And this is true, there is no `C:\tmp\dwminst\install.bat`.

**Comment by benmoss** [comment]
What is this from? Using the cloudformation template? Also, do you know which release version this was from?

**Comment by jvshahid** [comment]
> After small modification of the template (I just specified my CF/Diego's subnet) debug-stderr contains:
> 

What do you mean by modifying the template ? May be an example would help.

> panic: interface conversion: interface is nil, not string
> 
> goroutine 1 [running]:
> main.main()
>     C:/diego-windows-release/greenhouse-install-script-generator/src/generate/generate.go:138 +0x1f5e

It looks like the version you are using is not the most recent version.

> 'C:\tmp\dwminst\install.bat' is not recognized as an internal or external command,
> operable program or batch file.

This is normal since the generator crashed and failed to generate the files. We will add a check to make sure the generator succeeded before running the install script.
