### ISSUE TITLE
Required properties are not documented

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/diego-windows-release#21]
The following new properties are not listed in the documentation:

CONSUL_DOMAIN
REP_REQUIRE_TLS
REP_CA_CERT_FILE
REP_SERVER_CERT_FILE
REP_SERVER_KEY_FILE

**Comment by sunjayBhatia** [comment]
The recommended mechanism to install the MSIs is with the [install script generator](https://github.com/cloudfoundry-incubator/greenhouse-install-script-generator). If you would like to modify any of the parameters to the MSIs, you can edit the generated `install.bat` produced by the install script generator.
