### ISSUE TITLE
Rep TLS config is hard coded

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/diego-windows-release#22]
When the rep config was changed to pull from a file it's now using hard coded values for the TLS configuration:

https://github.com/cloudfoundry/diego-windows-release/blob/master/DiegoWindowsRelease/RepService/RepService.cs#L42-L45

It was previously pulling from the provided values:

https://github.com/cloudfoundry/diego-windows-release/blob/12830d1a97fa6bf30ec9490693f5fc6d98f0d58b/DiegoWindowsRelease/RepService/RepService.cs#L93-L96

**Comment by mhoran** [comment]
See the following commit for the changes: https://github.com/cloudfoundry/diego-windows-release/commit/c0c2eefaa055060a53fa8a95ef1f52c27ff5427a
