### ISSUE TITLE
QT Creator

### ISSUE THREAD

**Issue by abigdreamer** [cloudfoundry/diego-windows-release#23]
How could QT creator apps be built and deployed inside Cloud Foundry? This is the closest project I've found to this task. QT Creator is a C++ IDE.

**Comment by mdelillo** [comment]
Hi @abigdreamer, is QT Creator capable of building standalone binaries? If so, you can deploy that using the [binary-buildpack](https://github.com/cloudfoundry/binary-buildpack).

**Comment by sunjayBhatia** [comment]
Qt is a GUI application development framework, not really the target app for CF
