### ISSUE TITLE
cannot find generate.exe

### ISSUE THREAD

**Issue by trondhindenes** [cloudfoundry/diego-windows-release#25]
The documentation mentions a "generate.exe" tool, however, I cannot find it.

**Comment by sunjayBhatia** [comment]
@trondhindenes if you look in the releases for this repo, the `generate.exe` should be linked there

**Comment by trondhindenes** [comment]
Doc states that generate.exe is in the garden repo, while the correct location is the diego repo.

**Comment by sunjayBhatia** [comment]
Doc has been updated: https://github.com/cloudfoundry/diego-windows-release/blob/master/docs/INSTALL.md#install-the-msis closing this out
