### ISSUE TITLE
NoAppDetectedError while pushing dot net app on windows cell

### ISSUE THREAD

**Issue by cfmagnum** [cloudfoundry/diego-windows-release#27]
We have upgraded cf to v254 and diego v1.10.1. The windows cell has been deployed using diego-windows-release 0.496 ,but while pushing any app on stack windows2012R2 we get the following error:

```
x.x.x.x:~/workspace/oscf-old/ci/aws/windows-cell/wats/assets/nora/NoraPublished$ cf push windows-test-app -s windows2012R2 -b https://github.com/ryandotsmith/null-buildpack.git -m 1G --no-start
Using stack windows2012R2...
OK
Updating app windows-test-app in org oscf-sys / space testing as admin...
OK

Uploading windows-test-app...
Uploading app files from: /workspace/.jewel/oscf-old/ci/aws/windows-cell/wats/assets/nora/NoraPublished
Uploading 21K, 20 files
Done uploading
OK

x.x.x.x:~/workspace/oscf-old/ci/aws/windows-cell/wats/assets/nora/NoraPublished$ cf start windows-test-app
Starting app windows-test-app in org oscf-sys / space testing as admin...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (786.8K)
Staging...
None of the buildpacks detected a compatible application
Exit status 222
Staging failed: Exited with status 222
Destroying container
Successfully destroyed container

FAILED
NoAppDetectedError
```

**Comment by sunjayBhatia** [comment]
@cfmagnum with that version of diego, the Windows App Lifecycle has changed to actually use buildpacks. As such, you need to use the `hwc-buildpack` and change your push command to:

```
cf push windows-test-app -s windows2012R2 -b https://github.com/cloudfoundry-incubator/hwc-buildpack/releases/download/v2.3.3/hwc_buildpack-cached-v2.3.3.zip -m 1G --no-start
```

The WAL also does not support git urls (there is a bug in libGit2) so your url does in fact also need to be to an actual buildpack artifact, not a git repository.

**Comment by sunjayBhatia** [comment]
also @cfmagnum please consider moving to BOSH deployed Windows cells, the MSI will be officially deprecated soon

**Comment by cfmagnum** [comment]
Thank you for the suggestion, we would try it. Also had a query as you stated that MSI would be deprecated what would be the migration strategy for the same. Would diego handle the migrations of existing apps to the new windows cell deployment(deployed via bosh).

**Comment by sunjayBhatia** [comment]
@cfmagnum Existing apps will have to be evacuated to the new BOSH deployed cells and the old DiegoWindows cells shut down.

- Deploy your new Windows cells with BOSH
- Run the following on each of your DiegoWindows cells from an elevated Powershell session:

```
Set-Service RepService -startuptype "Disabled"

Invoke-WebRequest -Uri -UseBasicParsing http://localhost:1800/evacuate -Method Post

while ($true) {
    try {
        Get-WebRequest "http://localhost:1800/ping"
    } catch {
        [system.exception]
        break;
    }
}
```

- And then shut down your DiegoWindows cells

Apps should be evacuated and pushed onto running cells

**Comment by cfmagnum** [comment]
Thank you for your suggestions. The migration stratergy on windows cell we would try it.
The other suggestion regarding pushing of apps on windows cell using different buildpack worked for us.

**Comment by sunjayBhatia** [comment]
Sweet! I will close this out then, glad you got it working
